# This file was generated by 'rake generate_secret_token', and should
# not be made visible to public.
# If you have a load-balancing Redmine cluster, you will need to use the
# same version of this file on each machine. And be sure to restart your
# server when you modify this file.
#
# Your secret key for verifying cookie session data integrity. If you
# change this key, all old sessions will become invalid! Make sure the
# secret is at least 30 characters and all random, no regular words or
# you'll be exposed to dictionary attacks.
# RedmineApp::Application.config.secret_token = ENV['SECRET_TOKEN']
RedmineApp::Application.config.secret_token = "7dfa2b4adff27208e4ea1ec6ae4cce582c54df2ba9890d684405e309ec398d6a7af976af3d19761cf70ab63fc4c1be471ad37e7b9884cd5ebce5d157c7d34293"

