#百度翻译设置
#Hb6NFkkAPueUIcfOYaWvVnVN
# http://developer.baidu.com/wiki/index.php?title=%E5%B8%AE%E5%8A%A9%E6%96%87%E6%A1%A3%E9%A6%96%E9%A1%B5/%E7%99%BE%E5%BA%A6%E7%BF%BB%E8%AF%91/%E7%BF%BB%E8%AF%91API
baidu_fanyi:
  host: "http://openapi.baidu.com/public/2.0/bmt/translate?"
  client_id: "FZdVhFzQaWdLWzX9En8hHckY"
  from: "zh"
  to: "en"
